import type { Consulta } from "@/types";

export const mockConsultas: Consulta[] = [
  // María González (p1)
  {
    id: "c1",
    paciente_id: "p1",
    fecha: "2024-01-15",
    motivo: "Primera consulta. Evaluación inicial.",
    evolucion_anterior: "",
    adherencia: "muy_buena",
    sintomas: "Cansancio matutino. Hinchazón después de comer.",
    energia: "baja",
    hambre_saciedad: "Hambre constante a media mañana. Saciedad lenta.",
    observaciones: "Se realiza anamnesis completa. Se toman medidas basales.",
    cambios_acordados: "Eliminar ultraprocesados. Aumentar proteína en desayuno.",
    notas_privadas: "Muy receptiva. Buena candidata para adherencia.",
    conclusion: "Inicio de proceso. Pauta desayuno hipocalórico hiperproteico.",
    created_at: "2024-01-15T10:30:00Z",
  },
  {
    id: "c2",
    paciente_id: "p1",
    fecha: "2024-02-12",
    motivo: "Revisión al mes. Seguimiento inicial.",
    evolucion_anterior: "Ha bajado 2,4 kg en 4 semanas.",
    adherencia: "buena",
    sintomas: "Menos hinchazón. Sigue con algo de cansancio.",
    energia: "normal",
    hambre_saciedad: "Mejor control del hambre. Come más despacio.",
    observaciones: "Buen progreso. Refiere sentirse más ligera.",
    cambios_acordados: "Introducir snack proteico de tarde. Revisar hidratación.",
    notas_privadas: "Comentó que el entorno familiar dificulta los cambios en cenas.",
    conclusion: "Excelente primera revisión. Continuar con la pauta ajustando cena.",
    created_at: "2024-02-12T10:30:00Z",
  },
  {
    id: "c3",
    paciente_id: "p1",
    fecha: "2024-03-15",
    motivo: "Segunda revisión. Ajuste de plan.",
    evolucion_anterior: "1,8 kg más. Total: -4,2 kg desde inicio.",
    adherencia: "buena",
    sintomas: "Sin síntomas relevantes.",
    energia: "buena",
    hambre_saciedad: "Control muy bueno del hambre.",
    observaciones: "Se introduce ejercicio de fuerza ligero 2 veces por semana.",
    cambios_acordados: "Nueva pauta con más variedad. Incluir batch cooking.",
    notas_privadas: "",
    conclusion: "Evolución muy positiva. Se ajusta plan con más variedad para mantener motivación.",
    created_at: "2024-03-15T10:30:00Z",
  },
  // Carlos Martínez (p2) — balón gástrico
  {
    id: "c4",
    paciente_id: "p2",
    fecha: "2024-02-10",
    motivo: "Primera consulta post-colocación de balón gástrico.",
    evolucion_anterior: "Balón colocado el 20/01/2024.",
    adherencia: "regular",
    sintomas: "Náuseas moderadas primeras semanas. Vómitos ocasionales.",
    energia: "baja",
    hambre_saciedad: "Saciedad muy alta. No tiene hambre.",
    observaciones: "Fase de adaptación difícil. Se trabaja tolerancia alimentaria.",
    cambios_acordados: "Dieta líquida-semilíquida. Progresión muy gradual.",
    notas_privadas: "Muy ansioso. Llamadas frecuentes. Requiere más soporte.",
    conclusion: "Fase aguda de adaptación. Pauta semilíquida. Revisión en 2 semanas.",
    created_at: "2024-02-10T09:30:00Z",
  },
  {
    id: "c5",
    paciente_id: "p2",
    fecha: "2024-03-08",
    motivo: "Revisión a las 6 semanas del balón.",
    evolucion_anterior: "-5,2 kg desde colocación. Mejor tolerancia.",
    adherencia: "buena",
    sintomas: "Náuseas ocasionales. Sin vómitos en la última semana.",
    energia: "normal",
    hambre_saciedad: "Saciedad rápida. Empieza a tener algo de hambre.",
    observaciones: "Gran mejoría en tolerancia. Se introduce textura normal blanda.",
    cambios_acordados: "Dieta blanda variada. Introducir proteína sólida blanda.",
    notas_privadas: "Mucho más tranquilo. El peso bajando le motiva.",
    conclusion: "Evolución favorable. Transición a textura blanda.",
    created_at: "2024-03-08T09:30:00Z",
  },
  // Laura Fernández (p3)
  {
    id: "c6",
    paciente_id: "p3",
    fecha: "2024-03-05",
    motivo: "Primera consulta. Evaluación y objetivos.",
    evolucion_anterior: "",
    adherencia: "muy_buena",
    sintomas: "Distensión abdominal. Fatiga crónica.",
    energia: "baja",
    hambre_saciedad: "Picos de hambre emocional por la tarde.",
    observaciones: "Se trabaja relación con la comida. Historial de restricción.",
    cambios_acordados: "Plan sin restricción. Estructura horaria. Gestión emocional básica.",
    notas_privadas: "Historial de dietas restrictivas. Ir despacio.",
    conclusion: "Enfoque intuitive eating adaptado. Plan de estructura sin prohibición.",
    created_at: "2024-03-05T11:30:00Z",
  },
];
