import type { Paciente, BalanGastrico } from "@/types";

export const mockPacientes: Paciente[] = [
  {
    id: "p1",
    nombre: "María",
    apellidos: "González Ruiz",
    fecha_alta: "2024-01-15",
    fecha_nacimiento: "1985-03-22",
    sexo: "femenino",
    telefono: "612 345 678",
    email: "maria.gonzalez@email.com",
    objetivo_principal: "Pérdida de peso y mejora de energía",
    antecedentes: "Hipotiroidismo controlado con medicación desde 2018",
    patologias: "Hipotiroidismo",
    medicacion: "Levotiroxina 50mcg",
    alergias: "Ninguna conocida",
    intolerancias: "Intolerancia a la lactosa leve",
    preferencias_alimentarias: "Mediterránea, le gustan las legumbres",
    alimentos_no_gustan: "Hígado, vísceras",
    actividad_fisica: "moderado",
    horarios_habituales: "Trabaja de 9 a 18h. Come en casa.",
    hace_ayuno: false,
    ventana_ayuno: "",
    sintomas_digestivos: "Hinchazón ocasional por la tarde",
    observaciones_generales: "Muy motivada. Cumple bien con los cambios graduales.",
    notas_privadas: "Tiene estrés laboral alto. Revisar en próxima consulta.",
    tiene_balon_gastrico: false,
    activo: true,
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "p2",
    nombre: "Carlos",
    apellidos: "Martínez López",
    fecha_alta: "2024-02-10",
    fecha_nacimiento: "1978-07-14",
    sexo: "masculino",
    telefono: "654 987 321",
    email: "carlos.ml@gmail.com",
    objetivo_principal: "Control de peso post-balón gástrico",
    antecedentes: "Obesidad grado II. Colesterol elevado.",
    patologias: "Dislipemia, SAOS leve",
    medicacion: "Atorvastatina 20mg",
    alergias: "Penicilina",
    intolerancias: "Ninguna",
    preferencias_alimentarias: "Come de todo, prefiere carne a pescado",
    alimentos_no_gustan: "Verduras de hoja verde, brócoli",
    actividad_fisica: "ligero",
    horarios_habituales: "Turno partido. Cena tarde, sobre las 22h.",
    hace_ayuno: false,
    sintomas_digestivos: "Reflujo ocasional",
    observaciones_generales: "Fase de adaptación al balón. Buen progreso.",
    notas_privadas: "Muy ansioso en las primeras semanas. Ya más tranquilo.",
    tiene_balon_gastrico: true,
    activo: true,
    created_at: "2024-02-10T09:00:00Z",
  },
  {
    id: "p3",
    nombre: "Laura",
    apellidos: "Fernández Castro",
    fecha_alta: "2024-03-05",
    fecha_nacimiento: "1995-11-30",
    sexo: "femenino",
    telefono: "699 111 222",
    email: "laurafe@outlook.com",
    objetivo_principal: "Mejorar relación con la comida y composición corporal",
    antecedentes: "Ansiedad. SOP diagnosticado en 2022.",
    patologias: "Síndrome de ovario poliquístico (SOP)",
    medicacion: "Inositol, vitamina D",
    alergias: "Ninguna",
    intolerancias: "Intolerancia al gluten no celíaca",
    preferencias_alimentarias: "Vegetariana flexible. Come huevos y pescado.",
    alimentos_no_gustan: "Carne roja",
    actividad_fisica: "activo",
    horarios_habituales: "Teletrabajo. Horarios irregulares.",
    hace_ayuno: true,
    ventana_ayuno: "12/12 (no desayuna antes de las 10h)",
    sintomas_digestivos: "Distensión abdominal frecuente",
    observaciones_generales: "Paciente muy consciente. Necesita estructura.",
    notas_privadas: "Episodios de comer emocional los fines de semana.",
    tiene_balon_gastrico: false,
    activo: true,
    created_at: "2024-03-05T11:30:00Z",
  },
  {
    id: "p4",
    nombre: "Ana",
    apellidos: "Romero Vidal",
    fecha_alta: "2023-09-20",
    fecha_nacimiento: "1962-05-18",
    sexo: "femenino",
    telefono: "600 444 555",
    email: "ana.romero@hotmail.com",
    objetivo_principal: "Nutrición en menopausia y control de glucemia",
    antecedentes: "Menopausia. Prediabetes desde 2022.",
    patologias: "Prediabetes, menopausia",
    medicacion: "Metformina 500mg (revisión pendiente)",
    alergias: "Ninguna",
    intolerancias: "Intolerancia a la fructosa leve",
    preferencias_alimentarias: "Cocina tradicional española. Come de todo.",
    alimentos_no_gustan: "Picante, curry",
    actividad_fisica: "moderado",
    horarios_habituales: "Jubilada. Come a las 14h. Cena a las 21h.",
    hace_ayuno: false,
    sintomas_digestivos: "Ninguno relevante",
    observaciones_generales: "Gran adherencia. Muy puntual en revisiones.",
    notas_privadas: "",
    tiene_balon_gastrico: false,
    activo: true,
    created_at: "2023-09-20T10:00:00Z",
  },
];

export const mockBalonGastrico: BalanGastrico[] = [
  {
    id: "bg1",
    paciente_id: "p2",
    fecha_colocacion: "2024-01-20",
    fase: "adaptacion",
    tolerancia_general: "regular",
    nauseas: "leves",
    vomitos: "ocasionales",
    reflujo: "leve",
    estrenimiento: false,
    diarrea: false,
    saciedad: "alta",
    hambre_emocional: "alta",
    alimentos_peor_tolerados: "Carnes muy cocinadas, pan, pasta al dente",
    observaciones: "Mejora progresiva desde la tercera semana. Reflujo nocturno puntual.",
    updated_at: "2024-03-01T00:00:00Z",
  },
];
